// <auto-generated />
using AzurLaneBBot.Database.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AzurLaneBBot.Migrations
{
    [DbContext(typeof(AzurlanedbContext))]
    partial class AzurlanedbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("AzurLaneBBot.Database.Models.BoobaBotProject", b =>
                {
                    b.Property<string>("CoverageType")
                        .HasColumnType("TEXT");

                    b.Property<string>("CupSize")
                        .HasColumnType("TEXT");

                    b.Property<string>("IsSkinOf")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rarity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Shape")
                        .HasColumnType("TEXT");

                    b.ToTable("BOOBA_BOT_PROJECT", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
